/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.serioussem.se.money.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Account service. Represents a row in the &quot;se_money_Account&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ru.serioussem.se.money.model.impl.AccountModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ru.serioussem.se.money.model.impl.AccountImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Account
 * @generated
 */
@ProviderType
public interface AccountModel extends BaseModel<Account> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account model instance should use the {@link Account} interface instead.
	 */

	/**
	 * Returns the primary key of this account.
	 *
	 * @return the primary key of this account
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account.
	 *
	 * @param primaryKey the primary key of this account
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this account.
	 *
	 * @return the ID of this account
	 */
	public long getId();

	/**
	 * Sets the ID of this account.
	 *
	 * @param Id the ID of this account
	 */
	public void setId(long Id);

	/**
	 * Returns the name of this account.
	 *
	 * @return the name of this account
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this account.
	 *
	 * @param Name the name of this account
	 */
	public void setName(String Name);

	/**
	 * Returns the balance of this account.
	 *
	 * @return the balance of this account
	 */
	public double getBalance();

	/**
	 * Sets the balance of this account.
	 *
	 * @param Balance the balance of this account
	 */
	public void setBalance(double Balance);

	/**
	 * Returns the total of this account.
	 *
	 * @return the total of this account
	 */
	public boolean getTotal();

	/**
	 * Returns <code>true</code> if this account is total.
	 *
	 * @return <code>true</code> if this account is total; <code>false</code> otherwise
	 */
	public boolean isTotal();

	/**
	 * Sets whether this account is total.
	 *
	 * @param Total the total of this account
	 */
	public void setTotal(boolean Total);

}