/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.serioussem.se.money.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Operation service. Represents a row in the &quot;se_money_Operation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ru.serioussem.se.money.model.impl.OperationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ru.serioussem.se.money.model.impl.OperationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Operation
 * @generated
 */
@ProviderType
public interface OperationModel extends BaseModel<Operation> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a operation model instance should use the {@link Operation} interface instead.
	 */

	/**
	 * Returns the primary key of this operation.
	 *
	 * @return the primary key of this operation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this operation.
	 *
	 * @param primaryKey the primary key of this operation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this operation.
	 *
	 * @return the ID of this operation
	 */
	public long getId();

	/**
	 * Sets the ID of this operation.
	 *
	 * @param Id the ID of this operation
	 */
	public void setId(long Id);

	/**
	 * Returns the date of this operation.
	 *
	 * @return the date of this operation
	 */
	public Date getDate();

	/**
	 * Sets the date of this operation.
	 *
	 * @param Date the date of this operation
	 */
	public void setDate(Date Date);

	/**
	 * Returns the category ID of this operation.
	 *
	 * @return the category ID of this operation
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this operation.
	 *
	 * @param CategoryId the category ID of this operation
	 */
	public void setCategoryId(long CategoryId);

	/**
	 * Returns the sum of this operation.
	 *
	 * @return the sum of this operation
	 */
	public double getSum();

	/**
	 * Sets the sum of this operation.
	 *
	 * @param Sum the sum of this operation
	 */
	public void setSum(double Sum);

	/**
	 * Returns the comment of this operation.
	 *
	 * @return the comment of this operation
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this operation.
	 *
	 * @param Comment the comment of this operation
	 */
	public void setComment(String Comment);

}