/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.serioussem.se.money.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SubCategory service. Represents a row in the &quot;se_money_SubCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ru.serioussem.se.money.model.impl.SubCategoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ru.serioussem.se.money.model.impl.SubCategoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubCategory
 * @generated
 */
@ProviderType
public interface SubCategoryModel extends BaseModel<SubCategory> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sub category model instance should use the {@link SubCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this sub category.
	 *
	 * @return the primary key of this sub category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sub category.
	 *
	 * @param primaryKey the primary key of this sub category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this sub category.
	 *
	 * @return the ID of this sub category
	 */
	public long getId();

	/**
	 * Sets the ID of this sub category.
	 *
	 * @param Id the ID of this sub category
	 */
	public void setId(long Id);

	/**
	 * Returns the name of this sub category.
	 *
	 * @return the name of this sub category
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this sub category.
	 *
	 * @param Name the name of this sub category
	 */
	public void setName(String Name);

	/**
	 * Returns the parent category ID of this sub category.
	 *
	 * @return the parent category ID of this sub category
	 */
	public long getParentCategoryId();

	/**
	 * Sets the parent category ID of this sub category.
	 *
	 * @param ParentCategoryId the parent category ID of this sub category
	 */
	public void setParentCategoryId(long ParentCategoryId);

}